# Generated by Django 6.0.6 on 2026-06-05 07:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre de categoría')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('categoria_nutricional', models.CharField(choices=[('CER', 'Cereales'), ('LEG', 'Leguminosas'), ('TUB', 'Tubérculos'), ('VEG', 'Vegetales'), ('FRU', 'Frutas'), ('PRA', 'Proteína Animal'), ('HUE', 'Huevos'), ('LAC', 'Lácteos'), ('GRA', 'Grasas'), ('CON', 'Condimentos'), ('HIE', 'Hierbas'), ('EDU', 'Edulcorantes'), ('LIQ', 'Líquidos')], max_length=3, verbose_name='Categoría Nutricional')),
                ('unidad_medida', models.CharField(max_length=20, verbose_name='Unidad de medida')),
                ('origen', models.CharField(choices=[('NAC', 'Nacional'), ('IMP', 'Importado accesible')], max_length=3, verbose_name='Origen')),
                ('nivel_costo', models.CharField(choices=[('ME', 'Muy Económico'), ('EM', 'Económico Moderado'), ('NA', 'No Aplica')], max_length=2, verbose_name='Nivel de costo')),
                ('precio_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio actual')),
                ('fecha_precio', models.DateField(blank=True, null=True, verbose_name='Fecha del precio')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('porciones_base', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Porciones base')),
                ('calorias_por_porcion', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Calorías por porción (kcal)')),
                ('proteinas_g', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Proteínas por porción (g)')),
                ('carbohidratos_g', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Carbohidratos por porción (g)')),
                ('grasas_g', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Grasas por porción (g)')),
                ('fibra_g', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fibra por porción (g)')),
                ('nivel_costo', models.CharField(choices=[('ME', 'Muy Económico'), ('EM', 'Económico Moderado')], max_length=2, verbose_name='Nivel de costo')),
                ('notas_preparacion', models.TextField(blank=True, verbose_name='Notas de preparación')),
                ('es_vegetariana', models.BooleanField(default=False, verbose_name='Es vegetariana')),
                ('es_vegana', models.BooleanField(default=False, verbose_name='Es vegana')),
                ('es_sin_gluten', models.BooleanField(default=False, verbose_name='Es sin gluten')),
                ('es_sin_lactosa', models.BooleanField(default=False, verbose_name='Es sin lactosa')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
            },
        ),
        migrations.CreateModel(
            name='RecetaCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.categoria', verbose_name='Categoría')),
                ('fk_receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.receta', verbose_name='Receta')),
            ],
            options={
                'verbose_name': 'Categoría de Receta',
                'verbose_name_plural': 'Categorías de Recetas',
                'unique_together': {('fk_receta', 'fk_categoria')},
            },
        ),
        migrations.AddField(
            model_name='receta',
            name='categorias',
            field=models.ManyToManyField(related_name='recetas', through='catalogo.RecetaCategoria', to='catalogo.categoria', verbose_name='Categorías'),
        ),
        migrations.CreateModel(
            name='RecetaIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('nota_uso', models.CharField(blank=True, max_length=200, verbose_name='Nota de uso')),
                ('fk_ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.ingrediente', verbose_name='Ingrediente')),
                ('fk_receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.receta', verbose_name='Receta')),
            ],
            options={
                'verbose_name': 'Ingrediente de Receta',
                'verbose_name_plural': 'Ingredientes de Recetas',
                'unique_together': {('fk_receta', 'fk_ingrediente')},
            },
        ),
        migrations.AddField(
            model_name='receta',
            name='ingredientes',
            field=models.ManyToManyField(related_name='recetas', through='catalogo.RecetaIngrediente', to='catalogo.ingrediente', verbose_name='Ingredientes'),
        ),
        migrations.CreateModel(
            name='HistorialPrecioIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('fk_ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='catalogo.ingrediente', verbose_name='Ingrediente')),
            ],
            options={
                'verbose_name': 'Historial de Precio',
                'verbose_name_plural': 'Historiales de Precios',
                'indexes': [models.Index(fields=['fk_ingrediente', '-fecha'], name='catalogo_hi_fk_ingr_4309a4_idx')],
            },
        ),
    ]
