# Generated by Django 6.0.6 on 2026-06-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='temporada',
            field=models.CharField(choices=[('TODO', 'Todo el año'), ('PRIMAVERA', 'Primavera'), ('VERANO', 'Verano'), ('OTONO', 'Otoño'), ('INVIERNO', 'Invierno')], default='TODO', max_length=10, verbose_name='Temporada'),
        ),
    ]
