# Generated by Django 6.0.6 on 2026-07-17 05:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_ingrediente_temporada'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='presentacion_comercial',
            field=models.DecimalField(decimal_places=2, default=1000, help_text='Cantidad base por unidad comercial de compra. Ej: 1000 para un paquete de 1kg (gramos), 1000 para 1L (ml), 1 para ingredientes que se compran por unidad.', max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Presentación comercial'),
        ),
    ]
