# Generated by Django 6.0.6 on 2026-07-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_ingrediente_presentacion_comercial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='temporada',
            field=models.CharField(choices=[('TODO', 'Todo el año'), ('PRIMAVERA', 'Primavera'), ('VERANO', 'Verano'), ('INVIERNO', 'Invierno')], default='TODO', max_length=10, verbose_name='Temporada'),
        ),
    ]
