# Generated by Django 6.0.6 on 2026-06-05 07:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateField(auto_now_add=True, verbose_name='Fecha de generación')),
                ('sincronizada_at', models.DateTimeField(blank=True, null=True, verbose_name='Sincronizada el')),
            ],
            options={
                'verbose_name': 'Lista de Compra',
                'verbose_name_plural': 'Listas de Compras',
            },
        ),
        migrations.CreateModel(
            name='MenuSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('momento', models.CharField(choices=[('DESAYUNO', 'Desayuno'), ('ALMUERZO', 'Almuerzo'), ('CENA', 'Cena'), ('MERIENDA', 'Merienda')], max_length=20, verbose_name='Momento del día')),
            ],
            options={
                'verbose_name': 'Menú Semanal',
                'verbose_name_plural': 'Menús Semanales',
            },
        ),
        migrations.CreateModel(
            name='ItemListaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad total')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPRADO', 'Comprado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('actualizado_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('fk_ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_lista', to='catalogo.ingrediente', verbose_name='Ingrediente')),
            ],
            options={
                'verbose_name': 'Ítem de Lista de Compra',
                'verbose_name_plural': 'Ítems de Listas de Compras',
            },
        ),
    ]
