# Generated by Django 6.0.6 on 2026-06-05 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('planificacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listacompra',
            name='fk_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_compra', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='itemlistacompra',
            name='fk_lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='planificacion.listacompra', verbose_name='Lista de compra'),
        ),
        migrations.AddField(
            model_name='menusemanal',
            name='fk_receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menus', to='catalogo.receta', verbose_name='Receta'),
        ),
        migrations.AddField(
            model_name='menusemanal',
            name='fk_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='menusemanal',
            unique_together={('fk_usuario', 'fecha', 'momento')},
        ),
    ]
