# Generated by Django 6.0.6 on 2026-06-27 02:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_ingrediente_temporada'),
        ('planificacion', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredienteSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('momento', models.CharField(choices=[('DESAYUNO', 'Desayuno'), ('ALMUERZO', 'Almuerzo'), ('CENA', 'Cena'), ('MERIENDA', 'Merienda')], max_length=20, verbose_name='Momento del día')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('fk_ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredientes_semanales', to='catalogo.ingrediente', verbose_name='Ingrediente')),
                ('fk_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_semanales', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Ingrediente Semanal',
                'verbose_name_plural': 'Ingredientes Semanales',
                'unique_together': {('fk_usuario', 'fk_ingrediente', 'fecha', 'momento')},
            },
        ),
    ]
